site_name: TaskTonic
site_description: A Refreshing Approach to Python Concurrency
repo_url: https://github.com/208develop/TaskTonic
repo_name: 208develop/TaskTonic

use_directory_urls: false

theme:
  name: material
  palette:
    primary: teal
    accent: cyan
  features:
    - navigation.tabs
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - Core Concepts:
      - The Introduction: 'CoreConcepts/10 - TaskTonic  - The introduction.md'
      - Sparkling Programming: 'CoreConcepts/20 - TaskTonic - Sparkling Programming.md'
      - Timers Without Waiting: 'CoreConcepts/30 - TaskTonic - Timers without waiting.md'
      - Depending on State: 'CoreConcepts/40 - TaskTonic - Depending on your state.md'
      - At Your Service: 'CoreConcepts/50 - Tasktonic - At your service.md'
      - Active Data Store: 'CoreConcepts/60 - TaskTonic - Active data store.md'
      - Understanding ttCatalyst: 'CoreConcepts/70 - TaskTonic - Understanding the ttCatalyst.md'
      - Testing in ttDistiller: 'CoreConcepts/90 - TaskTonic - Testing in the ttDistiller.md'
  - The Toolbox:
      - Building UIs -> PySide6 and TaskTonic: 'TheToolbox/110 - TaskTonic - PySide UI the TaskTonic way.md'
      - Networking & Sockets: 'TheToolbox/120 - TaskTonic - Networking and Sockets.md'
#  - Tasting The Tonic: tasting-the-tonic.md
